const MainSubjectsSet = new Set([
  "CS1703 COMPILER DESIGN",
  "BA1710 INDUSTRIAL ENGINEERING MANAGEMENT",
  "CS1762 COMPILER DESIGN LAB",
  "CS1763 INTELLIGENT SYSTEMS LAB",
  "MA1502 PROBABILITY, STATISTICS AND STOCHASTIC PROCESSES",
  "CS1502 OPERATING SYSTEM",
  "CS 1508 COMPUTER NETWORKS-I",
  "CS 1509 SOFTWARE ENGINEERING",
  "CS 1561 OPERATING SYSTEM LAB",
  "CS 1566 SOFTWARE ENGINEERING AND OBJECT ORIENTED ANALYSIS LAB",
  "CS 1567 SCRIPTING LANGUAGE LAB",
  "MA1308 DISCRETE MATHEMATICS",
  "CS1302 DATA STRUCTURES",
  "CS1304 DIGITAL CIRCUITS AND LOGIC DESIGN",
  "CS1306 COMPUTER ORGANIZATION AND ARCHITECTURE",
  "CS1307 INTELLECTUAL PROPERTY RIGHT AND SOFTWARE",
  "CS1308 OBJECT ORIENTED CONCEPTS & PROGRAMMING USING C++",
  "CS1361 DATA STRUCTURES LAB",
  "CS1363 DIGITAL CIRCUITS & LOGIC DESIGN LAB",
  "CS1365 OBJECT ORIENTED CONCEPTS & PROGRAMMING USING C++ LAB",
]);

const MainSubjects = Array.from(MainSubjectsSet);

export default MainSubjects;
